#include "tim_int.h"

uint32_t volatile   *tim3_CR1 =   0x40000400,
                    *tim3_SR =    0x40000410,
                    *tim3_DIER =  0x4000040C,
                    *tim3_EGR =   0x40000414,
                    *tim3_CNT =   0x40000424,
                    *tim3_ARR =   0x4000042C,
                    *tim3_CCR1 =  0x40000434;

void tim3_start(void){
    *tim3_CNT = 0;
    *tim3_SR = 0; // Clean update event generated by the timer initial config
    *tim3_DIER = 1<<0; 	 // Update interrupt enable
    *tim3_ARR = 10000; // Max ARR
    *tim3_CR1 |= (1<<0); // EN
}

void TIM3_IRQHandler(void)
{
    static uint32_t count = 0, it = 0;
    if(count++ == 1000000){
        printf("TIM3_IRQHandler %04d\r\n", it++);
        count = 0;
    }
}